### ISSUE TITLE
Installation of Chocolatey fails with Hosted Agent

### ISSUE THREAD

**Issue by chances** [chrisism/VSTS.ChocolateyTools#3]
Adding the Install/Upgrade Chocolatey task plainly to a Build Definition, but execution fails:

```2017-05-12T10:33:13.6223262Z ##[section]Starting: Install/Upgrade Chocolatey
2017-05-12T10:33:13.6243269Z ==============================================================================
2017-05-12T10:33:13.6243269Z Task         : Chocolatey - Install/Upgrade
2017-05-12T10:33:13.6243269Z Description  : Will download and install/upgrade Chocolatey on the server. Will only install if not already installed.
2017-05-12T10:33:13.6243269Z Version      : 1.0.8
2017-05-12T10:33:13.6243269Z Author       : Jungerius IT
2017-05-12T10:33:13.6243269Z Help         : 
2017-05-12T10:33:13.6243269Z ==============================================================================
2017-05-12T10:33:13.6313265Z Preparing task execution handler.
2017-05-12T10:33:16.6773214Z Executing the powershell script: d:\a\_tasks\ChocolateyInstaller_e199cc5f-e83c-4ca1-875c-90f30ae23560\1.0.8\installchoco.ps1
2017-05-12T10:33:17.1323924Z Downloading and installing Chocolatey
2017-05-12T10:33:17.1323924Z 
2017-05-12T10:33:17.1323924Z 
2017-05-12T10:33:17.9722315Z chocInstall
2017-05-12T10:33:17.9951105Z Getting latest version of the Chocolatey package for download.
2017-05-12T10:33:18.0731142Z Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.5.
2017-05-12T10:33:19.6424405Z Downloading 7-Zip commandline tool prior to extraction.
2017-05-12T10:33:19.7725750Z Extracting d:\a\_temp\chocolatey\chocInstall\chocolatey.zip to d:\a\_temp\chocolatey\chocInstall...
2017-05-12T10:33:19.9725758Z Installing chocolatey on this machine
2017-05-12T10:33:20.3635744Z WARNING: Setting ChocolateyInstall Environment Variable on USER and not SYSTEM variables.
2017-05-12T10:33:20.3635744Z   This is due to either non-administrator install OR the process you are running is not being run as an Administrator.
2017-05-12T10:33:20.3635744Z 
2017-05-12T10:33:20.3635744Z 
2017-05-12T10:33:20.3645761Z Creating ChocolateyInstall as an environment variable (targeting 'User') 
2017-05-12T10:33:20.3645761Z   Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
2017-05-12T10:33:20.3645761Z WARNING: It's very likely you will need to close and reopen your shell 
2017-05-12T10:33:20.3645761Z   before you can use choco.
2017-05-12T10:33:20.3645761Z 
2017-05-12T10:33:20.3655756Z 
2017-05-12T10:33:20.7145753Z ##[error]System.Management.Automation.RuntimeException: Installation of Chocolatey to default folder requires Administrative permissions. Please run from elevated prompt. Please see https://chocolatey.org/install for details and alternatives if needing to install as a non-administrator. ---> System.Management.Automation.RuntimeException: Installation of Chocolatey to default folder requires Administrative permissions. Please run from elevated prompt. Please see https://chocolatey.org/install for details and alternatives if needing to install as a non-administrator.
2017-05-12T10:33:20.7145753Z    --- End of inner exception stack trace ---
2017-05-12T10:33:20.7185754Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-05-12T10:33:20.7225758Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-05-12T10:33:20.7295744Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-05-12T10:33:20.7305757Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-12T10:33:20.7305757Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-05-12T10:33:20.7305757Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-05-12T10:33:20.7315760Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
```

It looks like you may have said in the VS Marketplace this use case is not supported:

> At the moment remote installation is not supported.

Is this the case here too?

**Comment by felpel** [comment]
I've encountered exactly the same problem recently. Any feedback or help would be appreciated regarding this issue.

**Comment by chrisism** [comment]
The above case is due to the user (tfs/vsts agent) has not enough rights to invoke the chocolatey command from the commandline.
Keep in mind that is action is executed under the same user that the agent runs. So you might need to increase the privelleges of that particular user.

**Comment by felpel** [comment]
Have you been able to use it on the `Hosted VS2017` agent?

**Comment by chrisism** [comment]
I have only used it on a self hosted agent. You can try the chocolatey tools task from Microsoft. I myself am looking at other approaches in general, like using tools like chef or puppet etc.

**Comment by felpel** [comment]
We've decided to setup our own private agent and your task is working as it should. This issue may be closed.

**Comment by felpel** [comment]
We've decided to setup our own private agent and your task is working as it should. This issue may be closed.

**Comment by chrisism** [comment]
Thanks for the feedback
